# Generated by Django 4.1.3 on 2022-11-24 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='описание'),
        ),
    ]
