# Generated by Django 4.1.3 on 2022-12-05 15:35

import django.core.validators
from django.db import migrations, models
import task_tracker.customvalidation


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0002_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=40, null=True, validators=[task_tracker.customvalidation.banned_words], verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='описание')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='дата окончания')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=40, validators=[task_tracker.customvalidation.banned_words], verbose_name='заголовок'),
        ),
    ]
