# Generated by Django 4.1.3 on 2022-12-06 09:28

import django.core.validators
from django.db import migrations, models
import task_tracker.customvalidation


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0004_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='default description', max_length=300, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default='2022-12-06', verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='default title', max_length=40, validators=[task_tracker.customvalidation.banned_words], verbose_name='название'),
        ),
    ]
