# Generated by Django 4.1.3 on 2022-12-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0009_alter_task_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
            ],
        ),
    ]
