# Generated by Django 4.1.3 on 2022-12-21 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_tracker', '0014_remove_project_user_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(default=1, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(default=1, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
