# Generated by Django 4.1.3 on 2022-12-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_tracker', '0015_project_users_task_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('can_change_users', 'может удалять или добавлять пользователей')]},
        ),
    ]
