# Generated by Django 4.1.3 on 2022-12-21 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_tracker', '0016_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(default=1, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='пользователи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(default=1, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='пользователи'),
        ),
    ]
